### ISSUE TITLE
Can't Upload Document (.docx extensions)

### ISSUE THREAD

**Issue by farisgozi** [docs-ai/docs-ai#1]
I can't get my file to be uploaded, it says failed to upload. evenly my file not bigger than the maximum uploaded requirement. Any solution for this?

(Website)

**Comment by farisgozi** [comment]
> I can't get my file to be uploaded, it says failed to upload. evenly my file not bigger than the maximum uploaded requirement. Any solution for this?
> 
> (Website)

PS* ANY FILE CAN'T BE UPLOADED

**Comment by ShrihariMohan** [comment]
Hey @goziyyy ! docsai just exhausted all storage . We're going to increase it soon. I will let you know once we increase the limit . Thanks for trying docsai

**Comment by ShrihariMohan** [comment]
@goziyyy  This is fixed!
